# Generated by Django 4.0.4 on 2022-05-16 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0002_contact_phonenumber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phonenumber',
            old_name='question',
            new_name='contact',
        ),
    ]
